#!/bin/bash
SVC=$1
INST=$2
SVR_UUID=$3
 
[ ! "$1" ] && echo "Usage: sdc-create_service :SERVICE :INSTANCE :SERVER" && exit 1
[ ! "$2" ] && echo "Usage: sdc-create_service :SERVICE :INSTANCE :SERVER" && exit 1
[ ! "$3" ] && echo "Usage: sdc-create_service :SERVICE :INSTANCE :SERVER" && exit 1
 
SVC_UUID=$(sdc-sapi /services?name=$SVC | json -aH uuid)
[ ! "$SVC_UUID" ] && echo "Invalid service name $SVC" && exit 1

SVR_UUID2=$(sdc-cnapi /servers/$3 | json -aH uuid)
[ $SVR_UUID != "$SVR_UUID2" ] && echo "Invalid Server UUID $SVR_UUID" && exit 1
 
echo "Creating service instance $SVC$INST"
echo $SVC_UUID
echo '{"params":{}, "metadata":{} }' | json -e "service_uuid = '$SVC_UUID'; params.alias='$SVC$INST'; params.server_uuid='$SVR_UUID';" | sapiadm provision
